
address:
  country:
     UK:
        street:
          - "Ebon Route"
          - "Lavender Lane"
          - "Merchant Way"
          - "Brook Lane"
          - "Nova Boulevard"
          - "Cathedral Lane"
          - "Oceanview Route"
          - "Ember Avenue"
          - "Wetland Lane"
          - "Nightingale Lane"
          - "Elm Avenue"
          - "Crystal Boulevard"
          - "Starlight Street"
          - "Market Lane"
          - "Baker Boulevard"
          - "Providence Street"
          - "Beaver Avenue"
          - "Clearance Lane"
          - "Petal Lane"
          - "Juniper Way"
          - "Star Row"
          - "Grace Street"
          - "Centre Lane"
          - "Heirloom Boulevard"
          - "Cannon Avenue"
          - "Angel Row"
          - "Senna Row"
          - "University Lane"
          - "Honor Avenue"
          - "Crystal Boulevard"


        city:
          - "Gravesend"
          - "Beaminster"
          - "Belvoir"
          - "Arundel"
          - "Windsor"
          - "Builth"
          - "Framlingham"
          - "Weighton"
          - "Llandovery"
          - "Midurst"
          - "Romsey"
          - "Grimsby"
          - "Tynemouth"
          - "Calne"
          - "Ripley"
          - "Buckden"
          - "Caerphilly"
          - "Axbridge"
          - "Porchester"
          - "Otterburn"
          - "Billinghame"
          - "Hawarden"
          - "Carisbrooke"
          - "Woburn"
          - "Bodmin"
          - "Midurst"
          - "Gillingham"
          - "Dunstanburgh"
          - "Stretton"
          - "Montgomery"
     PL:
        street:
          - "ul. Polna"
          - "ul. Glowna"
          - "ul. Zaciszna"
          - "ul. Barwna"
          - "ul. Nowa"
          - "ul. Piwna"
          - "ul. Witanowa"
          - "ul. Ciasna"
          - "ul. Grunwaldzka"
          - "ul. Bajeczna"
          - "ul. Waska"
          - "ul. Saska"
          - "ul. Borno"
          - "ul. Gdanska"
          - "ul. Babel"
          - "ul. Meskowa"
          - "ul. Zywa"
          - "ul. Amber"
          - "ul. Techniczna"
          - "ul. Zastawna"
          - "ul. Mickiewicza"
          - "ul. Zarnowa"
          - "ul. Bitwy Oliwskiej"
          - "ul. Pomorska"
          - "ul. Adama Krasickiego"
          - "ul. Karola Markusa"
        city:
          - "Gdansk"
          - "Gdynia"
          - "Ilawa"
          - "Warszawa"
          - "Susz"
          - "Rumia"
          - "Pila"
          - "Grudziadz"
          - "Kwidzyn"
          - "Czestochowa"
          - "Wroclaw"
          - "Poznan"
          - "Zamosc"
          - "Szczescin"
          - "Bialystok"
          - "Morag"
          - "Lodz"
          - "Kalisz"
          - "Kielce"
          - "Kudowa Zdroj"
          - "Zakopane"
          - "Tarnow"
          - "Olsztyn"
          - "Sopot"
          - "Wladyslawowo"
          - "Brodnica"
     DE:
        street:
          - "Meininger Strasse"
          - "Lietzenburger Straße"
          - "Feldstrasse"
          - "Schönhauser Allee"
          - "Nuernbergerstrasse"
          - "Wastney Road The Gardens Manukau"
          - "Inge Beisheim Platz"
          - "Frankfurter Allee"
          - "Konstanzer Strasse"
          - "Park Str."
          - "Leipziger Straße"
          - "Marseiller Strasse"
          - "Nuernbergerstrasse"
          - "Schaarsteinweg"
        city:
          - "Klaber"
          - "Kalbitz"
          - "Hauer"
          - "Westerholm"
          - "Harscheidt"
          - "Luisenhof"
          - "Sindlingen"
          - "Wildeppenried"
          - "Oberwinter"
          - "Altscheid"
          - "Todtenweis"
          - "Steinach"
          - "Wildnis"
          - "Bassin"


